export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';
export const ORDER_DETAILS_RESET = 'ORDER_DETAILS_RESET';

export const ORDER_HISTORY_REQUEST = 'ORDER_HISTORY_REQUEST'
export const ORDER_HISTORY_SUCCESS = 'ORDER_HISTORY_SUCCESS'
export const ORDER_HISTORY_FAIL = 'ORDER_HISTORY_FAIL'

export const INITIATE_TRANSACTION_REQUEST = "INITIATE_TRANSACTION_REQUEST"
export const INITIATE_TRANSACTION_SUCCESS = "INITIATE_TRANSACTION_SUCCESS"
export const INITIATE_TRANSACTION_FAIL = "INITIATE_TRANSACTION_FAIL"
export const INITIATE_TRANSACTION_RESET = "INITIATE_TRANSACTION_RESET"

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';