export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST"
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS"
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL"

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL"

export const USER_SIGNOUT = "USER_SIGNOUT"

export const USER_SAVE_ADDRESS_REQUEST = "USER_SAVE_ADDRESS_REQUEST"
export const USER_SAVE_ADDRESS_SUCCESS = "USER_SAVE_ADDRESS_SUCCESS"
export const USER_SAVE_ADDRESS_FAIL = "USER_SAVE_ADDRESS_FAIL"

export const REMOVE_SAVED_ADDRESS_REQUEST = "REMOVE_SAVED_ADDRESS_REQUEST"
export const REMOVE_SAVED_ADDRESS_SUCCESS = "REMOVE_SAVED_ADDRESS_SUCCESS"
export const REMOVE_SAVED_ADDRESS_FAIL = "REMOVE_SAVED_ADDRESS_FAIL"

export const GET_USER = "GET_USER"

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';